project:
  type: manuscript
  pre-render: bash mermaid-to-pdf.sh

bibliography: references.bib
cache: true
citation: true
df-print: kable
fig-align: center
fig-width: 7
fig-height: 4
fig-dpi: 600
lang: en
lightbox: true
link-external-newwindow: true
mermaid:
  theme: default
number-sections: true
warning: false
message: false

format:
  html:
    theme: cosmo
    code-tools:
      source: https://github.com/camillemndn/danova
    css: styles.css
    fig-format: jpeg
    include-in-header:
      text: |
        <script defer data-domain="camillemondon.com" src="https://analytics.mondon.xyz/js/script.js"></script>
  arxiv-pdf:
    authorcols: true
    biblatexoptions:
      - style=authoryear
      - backend=biber
      - backref=true
    cite-method: biblatex
    colorlinks: false
    fig-format: pdf
    fig-pos: ht
    link-citations: true
    mermaid-format: png
    pdf-engine: pdflatex
