project:
  type: manuscript

bibliography: references.bib
cache: true
citation: true
df-print: kable
fig-align: center
fig-width: 7
fig-height: 4
fig-dpi: 300
lang: en
lightbox: true
link-external-newwindow: true
mermaid:
  theme: default
notebook-links: false
number-sections: true

format:
  html:
    theme: cosmo
    code-tools:
      source: https://github.com/camillemndn/danova
    css: styles.css
    execute:
      echo: true
      warning: false
      message: false
    fig-format: jpeg
    include-in-header:
      text: |
        <script defer data-domain="camillemondon.com" src="https://analytics.mondon.xyz/js/script.js"></script>
  arxiv-pdf:
    authorcols: true
    biblatexoptions:
      - style=authoryear
      - backend=biber
      - backref=true
    cite-method: biblatex
    colorlinks: false
    fig-format: pdf
    fig-pos: ht
    link-citations: true
    pdf-engine: pdflatex

knitr:
  opts_chunk:
    collapse: true
    warning: false
    message: false
    comment: "#>"
