# Appendix {.appendix .unnumbered}

## Residuals in temporal regression {.appendix .unnumbered}

```{r fig-residuals}
#| fig-cap: $\frac{\| \varepsilon (t) \|^2}{\| y(t) - \overline y (t) \|^2}$.
vnt |>
  select(!rsq) |>
  unnest(ssr_evol) |>
  ggplot(aes(t, ssr, color = region, group = province)) +
  geom_point() +
  geom_line() +
  facet_wrap(vars(region))
```

```{r fig-rsq-map}
#| fig-cap: $R^2 = 1 - \frac{\sum_t \| \varepsilon (t) \|^2}{\sum_t \| y(t) - \overline y (t) \|^2}$.
vietnam_provinces |>
  left_join(vnt, by = "province") |>
  ggplot(aes(fill = rsq)) +
  geom_sf() +
  scale_fill_viridis_c() +
  scale_x_continuous(breaks = seq(from = -180, to = 180, by = 2)) +
  labs(x = "Longitude", y = "Latitude", fill = "Region")
```

## Normality assumption {.appendix .unnumbered}

```{r normality}
vnt_pc <- pca.fd(c(vnt$t_max), nharm = 5)
pairs(vnt_pc$scores)
mvn(vnt_pc$scores, mvnTest = "mardia")
```

## Homogeneity of variances {.appendix .unnumbered}

```{r fig-variance_homogeneity}
#| fig-cap: Correlation function within the MDR region.

vnt_var <- var.fd(c(as.fd(vnt$t_max)))

tt <- seq(
  vnt_var$sbasis$rangeval[1],
  vnt_var$sbasis$rangeval[2],
  length.out = 401
)

z <- eval.bifd(tt, tt, vnt_var) # Covariance
z <- cor.fd(tt, c(as.fd(vnt$t_max))) # Correlation

df <- data.frame(
  x = rep(tt, each = length(tt)),
  y = rep(tt, times = length(tt)),
  z = as.vector(z)
)

ggplot(df, aes(x = x, y = y, z = z)) +
  geom_contour_filled() +
  labs(
    fill = "Correlation",
    x = "Temperature (deg. Celsius)", y = "Temperature (deg. Celsius)"
  )
```
